/* Generated by scripts/write-content-kit.mjs -- do not edit by hand.
 * Source: JSON files under content/
 */
window.ShantaraContent = {
  "site": {
    "id": "site",
    "locale": "en",
    "source": "handbook",
    "business_name": "Shantara Naturopathy Retreat",
    "legal_name": "Metropolis Forward LLP",
    "parent_institution": "Hygiene Nature Cure Hospital",
    "phone": [
      "+91 9553 600 100"
    ],
    "email": "heal@shantara.life",
    "website": "https://shantara.life",
    "social_links": [
      {
        "platform": "facebook",
        "url": "https://www.facebook.com/shantaranaturopathy"
      },
      {
        "platform": "instagram",
        "url": "https://www.instagram.com/shantaranaturopathyretreat"
      },
      {
        "platform": "linkedin",
        "url": "https://www.linkedin.com/company/shantaranaturopathy/"
      },
      {
        "platform": "youtube",
        "url": "https://www.youtube.com/@shantaranaturopathy"
      }
    ],
    "place": {
      "street": "Chennamangallur",
      "locality": "Kozhikode",
      "region": "Keralam",
      "postal_code": "673602",
      "country": "IN"
    },
    "land_acres": 4,
    "rooms_count": 52,
    "room_categories": 5,
    "built_up_sq_ft": 60000,
    "built_up_note": "[TO CONFIRM] Website previously showed 56,000+ sq. ft.; the handbook uses 60,000 sq. ft.",
    "therapies_count": 13,
    "guests_served_label": "25,000+",
    "guests_served_since": 2000,
    "primary_cta": "Book a Consultation",
    "form_chrome_cta": "Send your details",
    "form_field_keys": [
      "full_name",
      "phone",
      "email",
      "country",
      "notes"
    ],
    "schema_defaults": {
      "type": "MedicalClinic"
    },
    "stats": [
      {
        "value": "25,000+",
        "label": "guests since 2000"
      },
      {
        "value": "13",
        "label": "therapies"
      }
    ],
    "short_name": "Shantara",
    "whatsapp": "+91 9553 600 100",
    "land_acres_note": "Internal only. Never publish the acreage; say 'hilltop'.",
    "rooms_count_note": "Mention at most once on the website, never as a stat or heading."
  },
  "tariff": {
    "id": "tariff",
    "locale": "en",
    "status": "published",
    "source": "rate-control-sheet",
    "includes": [
      "Accommodation",
      "The programme and treatments prescribed by your doctor",
      "Daily doctor consultation",
      "Diagnostic tests, as advised by your doctor",
      "All therapeutic naturopathy meals",
      "Entertainment and activities",
      "Two complimentary recreational therapies per week",
      "Airport and railway transfers",
      "Attire provided for your stay, and its laundry"
    ],
    "excludes": [
      "Recreational therapies beyond the two complimentary per week",
      "Treatments beyond those prescribed by your doctor",
      "Personal laundry"
    ],
    "supplements": [
      {
        "label": "Non-participating companion",
        "basis": "Per person, per night"
      },
      {
        "label": "Extra bed or mattress",
        "basis": "Per bed, per night"
      }
    ],
    "payment_terms": [
      {
        "booked_before": "31 days or more before arrival",
        "at_confirmation": "30%",
        "balance": "70%, due 30 days before arrival"
      },
      {
        "booked_before": "30 days or less before arrival",
        "at_confirmation": "100%",
        "balance": "None"
      }
    ],
    "cancellation": [
      {
        "cancelled_before": "More than 30 days before arrival",
        "refund": "100%"
      },
      {
        "cancelled_before": "21 to 30 days before arrival",
        "refund": "50%"
      },
      {
        "cancelled_before": "20 days or less before arrival, no-show or early departure",
        "refund": "No refund"
      }
    ],
    "public_notes": [
      "Rates are per room, per night, and include all taxes.",
      "You can be quoted and pay in any currency shown on the tariff.",
      "A companion staying in a separate room is charged separately. Our team confirms the amount."
    ]
  },
  "medicalCategories": {
    "id": "medical-categories",
    "locale": "en",
    "source": "handbook",
    "note": "Eleven handbook clinical groupings — staff routing aid, not public IA.",
    "categories": [
      {
        "id": "metabolic-lifestyle",
        "name": "Metabolic & Lifestyle Health",
        "examples": [
          "Type 2 diabetes",
          "obesity",
          "fatty liver (NAFLD)",
          "prediabetes/insulin resistance",
          "dyslipidemia"
        ]
      },
      {
        "id": "inflammatory-musculoskeletal",
        "name": "Inflammatory & Musculoskeletal Rehabilitation",
        "examples": [
          "Arthritis",
          "gout",
          "low back/neck pain",
          "spondylosis",
          "IVDP",
          "fibromyalgia"
        ]
      },
      {
        "id": "hormonal-endocrine",
        "name": "Hormonal & Endocrine Balance",
        "examples": [
          "PCOS",
          "thyroid dysfunction",
          "menstrual irregularities",
          "perimenopause",
          "fertility-related hormonal imbalance"
        ]
      },
      {
        "id": "gastrointestinal",
        "name": "Gastrointestinal & Gut Health Restoration",
        "examples": [
          "IBS",
          "gastritis",
          "peptic ulcer",
          "colitis",
          "constipation",
          "dyspepsia"
        ]
      },
      {
        "id": "neurological-stress",
        "name": "Neurological & Stress-Related Conditions",
        "examples": [
          "Migraine",
          "chronic headaches",
          "burnout",
          "chronic stress",
          "insomnia",
          "mild anxiety"
        ]
      },
      {
        "id": "renal",
        "name": "Renal Health",
        "examples": [
          "Early-stage CKD",
          "diabetic/hypertensive nephropathy",
          "kidney stones",
          "microalbuminuria",
          "nephritis"
        ]
      },
      {
        "id": "heart-circulatory",
        "name": "Heart & Circulatory Health",
        "examples": [
          "Hypertension",
          "stable coronary artery disease",
          "cardiac rehab",
          "post-MI recovery",
          "post-angioplasty/CABG rehab"
        ]
      },
      {
        "id": "respiratory-immune",
        "name": "Respiratory & Immune Resilience",
        "examples": [
          "Asthma",
          "chronic bronchitis",
          "COPD",
          "allergic rhinitis",
          "sinusitis"
        ]
      },
      {
        "id": "dermatological",
        "name": "Dermatological & Skin Health",
        "examples": [
          "Acne",
          "dermatitis",
          "psoriasis",
          "eczema",
          "hyperpigmentation"
        ]
      },
      {
        "id": "reproductive-fertility",
        "name": "Reproductive & Fertility Optimization",
        "examples": [
          "Female/male infertility",
          "PCOS",
          "ovulatory dysfunction",
          "irregular cycles",
          "endometriosis"
        ]
      },
      {
        "id": "hematologic-nutritional",
        "name": "Hematologic & Nutritional Disorders",
        "examples": [
          "Anemia",
          "B12/D deficiency",
          "hypoproteinemia",
          "micronutrient deficiencies"
        ]
      }
    ],
    "status": "draft"
  },
  "programs": [
    {
      "id": "complete-healing",
      "slug": "complete-healing",
      "name": "Complete Healing",
      "focus": "Immersive",
      "proposition": "For guests managing several long-standing conditions at once, across metabolic, musculoskeletal and mental health.",
      "durations": "21–28 nights",
      "locale": "en",
      "source": "kit",
      "related_pages": [
        {
          "type": "therapy",
          "id": "mud-therapy"
        },
        {
          "type": "therapy",
          "id": "physiotherapy"
        },
        {
          "type": "therapy",
          "id": "diet-therapy"
        },
        {
          "type": "therapy",
          "id": "yoga-therapy"
        },
        {
          "type": "therapy",
          "id": "mind-body-therapy"
        }
      ],
      "status": "published",
      "featured_image": {
        "src": "courtyard",
        "alt": "The courtyard at Shantara"
      },
      "featured": true
    },
    {
      "id": "corporate-retreats",
      "slug": "corporate-retreats",
      "name": "Corporate Retreats",
      "focus": "Groups",
      "proposition": "Group programmes for teams, with therapies and schedule planned around group size and objectives.",
      "durations": "By arrangement",
      "locale": "en",
      "source": "kit",
      "related_pages": [
        {
          "type": "therapy",
          "id": "yoga-therapy"
        },
        {
          "type": "therapy",
          "id": "mind-body-therapy"
        },
        {
          "type": "therapy",
          "id": "massage-therapy"
        }
      ],
      "status": "published",
      "featured_image": {
        "src": "dining",
        "alt": "The dining room at Shantara"
      },
      "featured": true
    },
    {
      "id": "detox",
      "slug": "detox",
      "name": "Detox",
      "focus": "Metabolic",
      "proposition": "Your doctor may recommend a meal plan or supervised fasting based on your assessment. Therapies may also form part of your programme.",
      "durations": "7–21 nights",
      "locale": "en",
      "source": "kit",
      "related_pages": [
        {
          "type": "therapy",
          "id": "fasting-therapy"
        },
        {
          "type": "therapy",
          "id": "diet-therapy"
        },
        {
          "type": "therapy",
          "id": "hydrotherapy"
        },
        {
          "type": "therapy",
          "id": "heliotherapy"
        }
      ],
      "status": "published",
      "featured_image": {
        "src": "water-wall",
        "alt": "The water wall at the therapy wing"
      },
      "featured": true
    },
    {
      "id": "diabetes-reversal",
      "slug": "diabetes-reversal",
      "name": "Diabetes Reversal",
      "focus": "Clinical",
      "proposition": "Diet, activity and therapies planned around blood-sugar control, with medication reviewed by a doctor. Recommendations depend on your assessment.",
      "durations": "14–28 nights",
      "locale": "en",
      "source": "kit",
      "related_pages": [
        {
          "type": "therapy",
          "id": "diet-therapy"
        },
        {
          "type": "therapy",
          "id": "fasting-therapy"
        },
        {
          "type": "therapy",
          "id": "yoga-therapy"
        },
        {
          "type": "therapy",
          "id": "heliotherapy"
        }
      ],
      "status": "published",
      "featured_image": {
        "src": "treatment",
        "alt": "A treatment room at Shantara"
      },
      "featured": true
    },
    {
      "id": "executive-wellness",
      "slug": "executive-wellness",
      "name": "Executive Wellness",
      "focus": "Rest",
      "proposition": "A compact daily plan for guests who need to stay partly available for work.",
      "durations": "7–10 nights",
      "locale": "en",
      "source": "kit",
      "related_pages": [
        {
          "type": "therapy",
          "id": "yoga-therapy"
        },
        {
          "type": "therapy",
          "id": "mind-body-therapy"
        },
        {
          "type": "therapy",
          "id": "diet-therapy"
        }
      ],
      "status": "published",
      "featured_image": {
        "src": "library",
        "alt": "The library at Shantara"
      },
      "featured": true
    },
    {
      "id": "longevity",
      "slug": "longevity",
      "name": "Longevity",
      "focus": "Clinical",
      "proposition": "Preventive routines, metabolic and movement support, and doctor-guided reassessment for guests who want to stay capable and well. Catalogue programme, not a longevity-medicine product.",
      "durations": null,
      "locale": "en",
      "source": "handbook",
      "related_pages": [
        {
          "type": "therapy",
          "id": "physiotherapy"
        },
        {
          "type": "therapy",
          "id": "yoga-therapy"
        },
        {
          "type": "therapy",
          "id": "diet-therapy"
        },
        {
          "type": "therapy",
          "id": "heliotherapy"
        }
      ],
      "status": "published",
      "featured_image": {
        "src": "valley",
        "alt": "The valley below Shantara"
      },
      "featured": false
    },
    {
      "id": "mens-vitality",
      "slug": "mens-vitality",
      "name": "Men's Vitality",
      "focus": "Clinical",
      "proposition": "Supports energy, metabolic health, and hormone-related concerns through assessment-led routines, nourishment, activity, and rest. Matched after clinical review.",
      "durations": null,
      "locale": "en",
      "source": "handbook",
      "related_pages": [
        {
          "type": "therapy",
          "id": "diet-therapy"
        },
        {
          "type": "therapy",
          "id": "yoga-therapy"
        },
        {
          "type": "therapy",
          "id": "physiotherapy"
        }
      ],
      "status": "published",
      "featured_image": {
        "src": "grounds",
        "alt": "The grounds at Shantara"
      },
      "featured": false
    },
    {
      "id": "stress-management",
      "slug": "stress-management",
      "name": "Stress Management",
      "focus": "Mind",
      "proposition": "Doctor-led routines, therapies and rest for guests managing sustained stress, poor sleep or fatigue.",
      "durations": "7–14 nights",
      "locale": "en",
      "source": "kit",
      "related_pages": [
        {
          "type": "therapy",
          "id": "yoga-therapy"
        },
        {
          "type": "therapy",
          "id": "mind-body-therapy"
        },
        {
          "type": "therapy",
          "id": "hydrotherapy"
        },
        {
          "type": "therapy",
          "id": "mud-therapy"
        }
      ],
      "status": "published",
      "featured_image": {
        "src": "balcony",
        "alt": "A room balcony over the valley"
      },
      "featured": true
    },
    {
      "id": "weekend-rejuvenation",
      "slug": "weekend-rejuvenation",
      "name": "Weekend Rejuvenation",
      "focus": "Rest",
      "proposition": "A shorter stay for guests with limited time: rest, gentle therapies and meals planned for the programme.",
      "durations": "7 nights",
      "locale": "en",
      "source": "kit",
      "related_pages": [
        {
          "type": "therapy",
          "id": "yoga-therapy"
        },
        {
          "type": "therapy",
          "id": "massage-therapy"
        },
        {
          "type": "therapy",
          "id": "hydrotherapy"
        }
      ],
      "status": "published",
      "featured_image": {
        "src": "lounge",
        "alt": "The lounge at Shantara"
      },
      "featured": true
    },
    {
      "id": "weight-management",
      "slug": "weight-management",
      "name": "Weight Management",
      "focus": "Metabolic",
      "proposition": "Meals, daily activity and therapies, with weight and vitals reviewed by a doctor each morning.",
      "durations": "14–21 nights",
      "locale": "en",
      "source": "kit",
      "related_pages": [
        {
          "type": "therapy",
          "id": "diet-therapy"
        },
        {
          "type": "therapy",
          "id": "yoga-therapy"
        },
        {
          "type": "therapy",
          "id": "hydrotherapy"
        },
        {
          "type": "therapy",
          "id": "physiotherapy"
        }
      ],
      "status": "published",
      "featured_image": {
        "src": "grounds",
        "alt": "The grounds at Shantara"
      },
      "featured": true
    }
  ],
  "conditions": [
    {
      "id": "arthritis",
      "slug": "arthritis",
      "name": "Arthritis",
      "summary": "Therapies, movement and rest may be recommended to support joint comfort, following assessment.",
      "clinical": null,
      "faqs": [],
      "medical_reviewer": null,
      "last_medically_reviewed": null,
      "note": null,
      "locale": "en",
      "source": "kit",
      "related_pages": [
        {
          "type": "programme",
          "id": "complete-healing"
        }
      ],
      "category": "Musculoskeletal",
      "status": "draft",
      "featured_image": {
        "src": "treatment",
        "alt": "A treatment room at Shantara"
      },
      "external_references": []
    },
    {
      "id": "asthma",
      "slug": "asthma",
      "name": "Asthma",
      "summary": null,
      "clinical": null,
      "faqs": [],
      "medical_reviewer": null,
      "last_medically_reviewed": null,
      "locale": "en",
      "source": "gap",
      "related_pages": [
        {
          "type": "programme",
          "id": "complete-healing"
        }
      ],
      "category": null,
      "status": "draft",
      "featured_image": null,
      "external_references": []
    },
    {
      "id": "back-pain",
      "slug": "back-pain",
      "name": "Low back / neck pain",
      "summary": null,
      "clinical": null,
      "faqs": [],
      "medical_reviewer": null,
      "last_medically_reviewed": null,
      "locale": "en",
      "source": "gap",
      "related_pages": [
        {
          "type": "programme",
          "id": "complete-healing"
        }
      ],
      "category": null,
      "status": "draft",
      "featured_image": null,
      "external_references": []
    },
    {
      "id": "diabetes",
      "slug": "diabetes",
      "name": "Diabetes",
      "summary": "Residential programmes planned around blood-sugar control, meals and daily doctor review.",
      "clinical": null,
      "faqs": [],
      "medical_reviewer": null,
      "last_medically_reviewed": null,
      "note": null,
      "locale": "en",
      "source": "kit",
      "related_pages": [
        {
          "type": "programme",
          "id": "diabetes-reversal"
        },
        {
          "type": "programme",
          "id": "weight-management"
        },
        {
          "type": "programme",
          "id": "detox"
        },
        {
          "type": "programme",
          "id": "complete-healing"
        }
      ],
      "category": "Metabolic",
      "status": "draft",
      "featured_image": {
        "src": "dining",
        "alt": "The dining room at Shantara"
      },
      "external_references": []
    },
    {
      "id": "fatty-liver",
      "slug": "fatty-liver",
      "name": "Fatty liver (NAFLD)",
      "summary": null,
      "clinical": null,
      "faqs": [],
      "medical_reviewer": null,
      "last_medically_reviewed": null,
      "locale": "en",
      "source": "gap",
      "related_pages": [
        {
          "type": "programme",
          "id": "weight-management"
        },
        {
          "type": "programme",
          "id": "detox"
        }
      ],
      "category": null,
      "status": "draft",
      "featured_image": null,
      "external_references": []
    },
    {
      "id": "gastritis",
      "slug": "gastritis",
      "name": "Gastritis",
      "summary": null,
      "clinical": null,
      "faqs": [],
      "medical_reviewer": null,
      "last_medically_reviewed": null,
      "locale": "en",
      "source": "gap",
      "related_pages": [
        {
          "type": "programme",
          "id": "detox"
        }
      ],
      "category": null,
      "status": "draft",
      "featured_image": null,
      "external_references": []
    },
    {
      "id": "hypertension",
      "slug": "hypertension",
      "name": "Hypertension",
      "summary": null,
      "clinical": null,
      "faqs": [],
      "medical_reviewer": null,
      "last_medically_reviewed": null,
      "locale": "en",
      "source": "gap",
      "related_pages": [
        {
          "type": "programme",
          "id": "complete-healing"
        },
        {
          "type": "programme",
          "id": "detox"
        }
      ],
      "category": null,
      "status": "draft",
      "featured_image": null,
      "external_references": []
    },
    {
      "id": "ibs",
      "slug": "ibs",
      "name": "IBS",
      "summary": null,
      "clinical": null,
      "faqs": [],
      "medical_reviewer": null,
      "last_medically_reviewed": null,
      "locale": "en",
      "source": "gap",
      "related_pages": [
        {
          "type": "programme",
          "id": "detox"
        },
        {
          "type": "programme",
          "id": "complete-healing"
        }
      ],
      "category": null,
      "status": "draft",
      "featured_image": null,
      "external_references": []
    },
    {
      "id": "insomnia",
      "slug": "insomnia",
      "name": "Insomnia",
      "summary": null,
      "clinical": null,
      "faqs": [],
      "medical_reviewer": null,
      "last_medically_reviewed": null,
      "locale": "en",
      "source": "gap",
      "related_pages": [
        {
          "type": "programme",
          "id": "stress-management"
        }
      ],
      "category": null,
      "status": "draft",
      "featured_image": null,
      "external_references": []
    },
    {
      "id": "menopause",
      "slug": "menopause",
      "name": "Perimenopause",
      "summary": null,
      "clinical": null,
      "faqs": [],
      "medical_reviewer": null,
      "last_medically_reviewed": null,
      "locale": "en",
      "source": "gap",
      "related_pages": [
        {
          "type": "programme",
          "id": "complete-healing"
        }
      ],
      "category": null,
      "status": "draft",
      "featured_image": null,
      "external_references": []
    },
    {
      "id": "migraine",
      "slug": "migraine",
      "name": "Migraine",
      "summary": null,
      "clinical": null,
      "faqs": [],
      "medical_reviewer": null,
      "last_medically_reviewed": null,
      "locale": "en",
      "source": "gap",
      "related_pages": [
        {
          "type": "programme",
          "id": "stress-management"
        },
        {
          "type": "programme",
          "id": "complete-healing"
        }
      ],
      "category": null,
      "status": "draft",
      "featured_image": null,
      "external_references": []
    },
    {
      "id": "obesity",
      "slug": "obesity",
      "name": "Obesity",
      "summary": "Meals, activity and therapies, with weight and vitals reviewed each morning.",
      "clinical": null,
      "faqs": [],
      "medical_reviewer": null,
      "last_medically_reviewed": null,
      "locale": "en",
      "source": "kit",
      "note": "Launch slug for /en/conditions/obesity — not a kit listing card (weight-management need card covers the sample).",
      "related_pages": [
        {
          "type": "programme",
          "id": "weight-management"
        },
        {
          "type": "programme",
          "id": "diabetes-reversal"
        },
        {
          "type": "programme",
          "id": "detox"
        }
      ],
      "category": null,
      "status": "draft",
      "featured_image": null,
      "external_references": []
    },
    {
      "id": "pcos",
      "slug": "pcos",
      "name": "PCOS",
      "summary": "A programme may be planned around hormonal health, meals, activity and rest, following assessment.",
      "clinical": null,
      "faqs": [],
      "medical_reviewer": null,
      "last_medically_reviewed": null,
      "note": null,
      "locale": "en",
      "source": "kit",
      "related_pages": [
        {
          "type": "programme",
          "id": "complete-healing"
        },
        {
          "type": "programme",
          "id": "detox"
        }
      ],
      "category": "Hormonal",
      "status": "draft",
      "featured_image": {
        "src": "lounge",
        "alt": "The lounge at Shantara"
      },
      "external_references": []
    },
    {
      "id": "thyroid",
      "slug": "thyroid",
      "name": "Thyroid dysfunction",
      "summary": null,
      "clinical": null,
      "faqs": [],
      "medical_reviewer": null,
      "last_medically_reviewed": null,
      "locale": "en",
      "source": "gap",
      "related_pages": [
        {
          "type": "programme",
          "id": "complete-healing"
        }
      ],
      "category": null,
      "status": "draft",
      "featured_image": null,
      "external_references": []
    },
    {
      "id": "weight-management",
      "slug": "weight-management",
      "name": "Weight management",
      "summary": "Meals, activity and therapies, with weight and vitals reviewed each morning.",
      "clinical": null,
      "faqs": [],
      "medical_reviewer": null,
      "last_medically_reviewed": null,
      "note": "Listing need-card sample; distinct from the Weight Management programme entity.",
      "locale": "en",
      "source": "kit",
      "related_pages": [
        {
          "type": "programme",
          "id": "weight-management"
        },
        {
          "type": "programme",
          "id": "detox"
        }
      ],
      "category": "Metabolic",
      "status": "draft",
      "featured_image": {
        "src": "grounds",
        "alt": "The grounds at Shantara"
      },
      "external_references": []
    }
  ],
  "therapies": [
    {
      "id": "acupuncture",
      "name": "Acupuncture",
      "description": "Fine needles used to ease pain, when recommended by your doctor.",
      "slug": "acupuncture",
      "locale": "en",
      "source": "kit",
      "status": "published",
      "featured": true
    },
    {
      "id": "diet-therapy",
      "name": "Diet Therapy",
      "description": "Meals planned for your programme and reviewed as your stay progresses.",
      "slug": "diet-therapy",
      "locale": "en",
      "source": "kit",
      "status": "published",
      "featured": true
    },
    {
      "id": "fasting-therapy",
      "name": "Fasting Therapy",
      "description": "Introduced gradually and supervised by a doctor throughout.",
      "slug": "fasting-therapy",
      "locale": "en",
      "source": "kit",
      "status": "published",
      "featured": true
    },
    {
      "id": "heliotherapy",
      "name": "Heliotherapy",
      "description": "Controlled sunlight exposure, scheduled in the early morning.",
      "slug": "heliotherapy",
      "locale": "en",
      "source": "kit",
      "status": "published",
      "featured": true
    },
    {
      "id": "herbal-medicine",
      "name": "Herbal Medicine",
      "description": "Plant-based formulations selected to complement other therapies when recommended.",
      "slug": "herbal-medicine",
      "locale": "en",
      "source": "handbook",
      "status": "published",
      "featured": false
    },
    {
      "id": "hijama",
      "name": "Hijama",
      "description": "Traditional cupping, delivered under medical supervision.",
      "slug": "hijama",
      "locale": "en",
      "source": "kit",
      "status": "published",
      "featured": true
    },
    {
      "id": "hydrotherapy",
      "name": "Hydrotherapy",
      "description": "Water at controlled temperatures to support circulation.",
      "slug": "hydrotherapy",
      "locale": "en",
      "source": "kit",
      "status": "published",
      "featured": true
    },
    {
      "id": "manual-therapy",
      "name": "Manual Therapy",
      "description": "Hands-on techniques to support joint mobility and reduce stiffness.",
      "slug": "manual-therapy",
      "locale": "en",
      "source": "handbook",
      "status": "published",
      "featured": false
    },
    {
      "id": "massage-therapy",
      "name": "Massage Therapy",
      "description": "Therapeutic touch to ease muscle tension and support rest.",
      "slug": "massage-therapy",
      "locale": "en",
      "source": "handbook",
      "status": "published",
      "featured": false
    },
    {
      "id": "mind-body-therapy",
      "name": "Mind-Body Therapy",
      "description": "Guided practices to reduce stress and support emotional balance.",
      "slug": "mind-body-therapy",
      "locale": "en",
      "source": "handbook",
      "status": "published",
      "featured": false
    },
    {
      "id": "mud-therapy",
      "name": "Mud Therapy",
      "description": "Mineral-rich earth applied to calm inflammation and ease physical tension.",
      "slug": "mud-therapy",
      "locale": "en",
      "source": "kit",
      "status": "published",
      "featured": true
    },
    {
      "id": "physiotherapy",
      "name": "Physiotherapy",
      "description": "Guided exercises and hands-on therapy to support strength, mobility, and posture.",
      "slug": "physiotherapy",
      "locale": "en",
      "source": "handbook",
      "status": "published",
      "featured": false
    },
    {
      "id": "yoga-therapy",
      "name": "Yoga Therapy",
      "description": "Gentle movement and breathwork adapted to the individual.",
      "slug": "yoga-therapy",
      "locale": "en",
      "source": "kit",
      "status": "published",
      "featured": true
    }
  ],
  "rooms": [
    {
      "id": "executive-suite",
      "slug": "executive-suite",
      "name": "Executive Suite",
      "size": "530 sq.ft",
      "occupancy": "Single or double",
      "balcony": true,
      "spec_line": "530 sq.ft suite · balcony",
      "locale": "en",
      "source": "kit",
      "amenities": [
        "En-suite bathroom with rain shower",
        "Individually controlled central air-conditioning",
        "Orthopaedic mattress",
        "Electronic safe, Wi-Fi, smart LED TV"
      ],
      "status": "published",
      "featured_image": {
        "src": "room-premium",
        "alt": "A room with a balcony over the valley"
      },
      "featured": true
    },
    {
      "id": "junior-suite",
      "slug": "junior-suite",
      "name": "Junior Suite",
      "size": "420 sq.ft",
      "occupancy": "Single or double",
      "balcony": false,
      "spec_line": "420 sq.ft suite",
      "locale": "en",
      "source": "handbook",
      "amenities": [
        "En-suite bathroom with rain shower",
        "Individually controlled central air-conditioning",
        "Orthopaedic mattress",
        "Electronic safe, Wi-Fi, smart LED TV"
      ],
      "status": "published",
      "featured_image": {
        "src": "room-bedroom-forest-view-armchair",
        "alt": "A suite bedroom with a forest view"
      },
      "featured": false
    },
    {
      "id": "premium-room",
      "slug": "premium-room",
      "name": "Premium Room",
      "size": "460 sq.ft",
      "occupancy": "Single or double",
      "balcony": true,
      "spec_line": "460 sq.ft room · balcony",
      "locale": "en",
      "source": "kit",
      "amenities": [
        "En-suite bathroom with rain shower",
        "Individually controlled central air-conditioning",
        "Orthopaedic mattress",
        "Electronic safe, Wi-Fi, smart LED TV"
      ],
      "status": "published",
      "featured_image": {
        "src": "room-twin",
        "alt": "A guest room at Shantara"
      },
      "featured": true
    },
    {
      "id": "standard-room",
      "slug": "standard-room",
      "name": "Standard Room",
      "size": "260 sq.ft",
      "occupancy": "Single or double",
      "balcony": false,
      "spec_line": "260 sq.ft room",
      "locale": "en",
      "source": "kit",
      "amenities": [
        "En-suite bathroom with rain shower",
        "Individually controlled central air-conditioning",
        "Orthopaedic mattress",
        "Electronic safe, Wi-Fi, smart LED TV"
      ],
      "status": "published",
      "featured_image": {
        "src": "room-twin",
        "alt": "A guest room at Shantara"
      },
      "featured": false
    },
    {
      "id": "superior-room",
      "slug": "superior-room",
      "name": "Superior Room",
      "size": "300 sq.ft",
      "occupancy": "Single or double",
      "balcony": true,
      "spec_line": "300 sq.ft room · balcony",
      "locale": "en",
      "source": "kit",
      "amenities": [
        "En-suite bathroom with rain shower",
        "Individually controlled central air-conditioning",
        "Orthopaedic mattress",
        "Electronic safe, Wi-Fi, smart LED TV"
      ],
      "status": "published",
      "featured_image": {
        "src": "balcony",
        "alt": "A room balcony over the valley"
      },
      "featured": true
    }
  ],
  "doctors": [
    {
      "id": "bahja-janu",
      "slug": "bahja-janu",
      "full_name": "Dr. Bahja Janu",
      "role": "Medical Director",
      "photo_profile": "doctor-bahja-janu-portrait-cropped.jpeg",
      "qualification": null,
      "years_practice": null,
      "publications_note": null,
      "biography": null,
      "areas_of_practice": [],
      "locale": "en",
      "source": "handbook",
      "status": "draft",
      "featured_image": {
        "src": "doctor-bahja-janu-portrait",
        "alt": "Dr. Bahja Janu"
      }
    },
    {
      "id": "pa-kareem",
      "slug": "pa-kareem",
      "full_name": "Dr. P.A. Kareem",
      "role": "Founder, Chairman & Chief Naturopathy Consultant",
      "qualification": "Government of India-certified Naturopathy Practitioner",
      "years_practice": "26+",
      "publications_note": "Author of 17 books on naturopathy (Malayalam, English, Arabic)",
      "biography": "Founded Hygiene Nature Cure Hospital in 2000. Core approach: treat the cause through ethical, drug-free naturopathy.",
      "areas_of_practice": [
        "Naturopathy"
      ],
      "locale": "en",
      "source": "handbook",
      "status": "published"
    }
  ],
  "articles": [
    {
      "id": "how-meals-are-planned",
      "slug": "how-meals-are-planned",
      "title": "How meals are planned during a stay",
      "category": "Food & Recipes",
      "read_minutes": 4,
      "lead": "How meals are planned around your programme and dietary requirements.",
      "body": null,
      "author": null,
      "medical_reviewer": null,
      "kit_journal": true,
      "locale": "en",
      "source": "kit",
      "status": "draft",
      "featured_image": {
        "src": "dining",
        "alt": "The dining room at Shantara"
      }
    },
    {
      "id": "how-programme-duration-is-decided",
      "slug": "how-programme-duration-is-decided",
      "title": "How programme duration is decided",
      "category": "Clinical Guides",
      "read_minutes": 5,
      "lead": "How doctors advise the length of a stay after consultation and assessment.",
      "body": null,
      "author": null,
      "medical_reviewer": null,
      "kit_journal": true,
      "locale": "en",
      "source": "kit",
      "status": "draft",
      "featured_image": {
        "src": "corridor",
        "alt": "A corridor at Shantara"
      }
    },
    {
      "id": "how-rooms-are-designed",
      "slug": "how-rooms-are-designed",
      "title": "How our rooms are designed",
      "category": "Guest Stories",
      "read_minutes": 5,
      "lead": "Why the rooms are quiet, plain and easy to rest in.",
      "body": null,
      "author": null,
      "medical_reviewer": null,
      "kit_journal": true,
      "locale": "en",
      "source": "kit",
      "status": "draft",
      "featured_image": {
        "src": "room-premium",
        "alt": "A room with a balcony over the valley"
      }
    },
    {
      "id": "managing-pcos-lifestyle",
      "slug": "managing-pcos-lifestyle",
      "title": "Managing PCOS Through Lifestyle Change",
      "category": "Clinical Guides",
      "read_minutes": null,
      "lead": "Educational guide placeholder — body pending medical review.",
      "body": null,
      "author": null,
      "medical_reviewer": null,
      "kit_journal": false,
      "locale": "en",
      "source": "gap",
      "status": "draft",
      "featured_image": {
        "src": "lounge",
        "alt": "The lounge at Shantara"
      }
    },
    {
      "id": "naturopathy-assessment",
      "slug": "naturopathy-assessment",
      "title": "What Happens During a Naturopathy Assessment?",
      "category": "Clinical Guides",
      "read_minutes": null,
      "lead": "Educational guide placeholder — body pending medical review.",
      "body": null,
      "author": null,
      "medical_reviewer": null,
      "kit_journal": false,
      "locale": "en",
      "source": "gap",
      "status": "draft",
      "featured_image": {
        "src": "corridor",
        "alt": "A corridor at Shantara"
      }
    },
    {
      "id": "twenty-six-years",
      "slug": "twenty-six-years",
      "title": "Twenty-six years of treating the cause",
      "category": "Clinical Guides",
      "read_minutes": 3,
      "lead": "Dr. P.A. Kareem on drug-free practice since 2000.",
      "body": null,
      "author": null,
      "medical_reviewer": null,
      "kit_journal": true,
      "locale": "en",
      "source": "kit",
      "status": "draft",
      "featured_image": {
        "src": "library",
        "alt": "The library at Shantara"
      }
    },
    {
      "id": "understanding-insulin-resistance",
      "slug": "understanding-insulin-resistance",
      "title": "Understanding Insulin Resistance",
      "category": "Clinical Guides",
      "read_minutes": null,
      "lead": "Educational guide placeholder — body pending medical review.",
      "body": null,
      "author": null,
      "medical_reviewer": null,
      "kit_journal": false,
      "locale": "en",
      "source": "gap",
      "status": "draft",
      "featured_image": {
        "src": "treatment",
        "alt": "A treatment room at Shantara"
      }
    },
    {
      "id": "week-of-monsoon-light",
      "slug": "week-of-monsoon-light",
      "title": "A week of monsoon light",
      "category": "Guest Stories",
      "read_minutes": 6,
      "lead": "A hilltop above Chennamangallur, hour by hour.",
      "body": null,
      "author": null,
      "medical_reviewer": null,
      "kit_journal": true,
      "locale": "en",
      "source": "kit",
      "status": "draft",
      "featured_image": {
        "src": "valley",
        "alt": "The valley below Shantara"
      }
    }
  ],
  "doctorAnswers": [
    {
      "id": "continue-medication",
      "slug": "continue-existing-medication",
      "question": "Can I continue my existing medication during a naturopathy stay?",
      "short_answer": null,
      "detailed_answer": null,
      "doctor_id": null,
      "read_minutes": null,
      "category": "Doctor Answers",
      "kit_journal": false,
      "locale": "en",
      "source": "gap",
      "status": "draft",
      "featured_image": null,
      "external_references": []
    },
    {
      "id": "first-consultation",
      "slug": "first-naturopathy-consultation",
      "question": "What happens in the first naturopathy consultation?",
      "short_answer": null,
      "detailed_answer": null,
      "doctor_id": null,
      "read_minutes": null,
      "category": "Doctor Answers",
      "kit_journal": false,
      "locale": "en",
      "source": "gap",
      "status": "draft",
      "featured_image": null,
      "external_references": []
    },
    {
      "id": "supervised-fast-feels-like",
      "slug": "what-a-supervised-fast-actually-feels-like",
      "question": "What a supervised fast actually feels like",
      "short_answer": "How a supervised fast is introduced, monitored and ended.",
      "detailed_answer": null,
      "doctor_id": null,
      "read_minutes": 7,
      "category": "Doctor Answers",
      "kit_journal": true,
      "locale": "en",
      "source": "kit",
      "status": "draft",
      "featured_image": {
        "src": "treatment",
        "alt": "A treatment room at Shantara"
      },
      "external_references": []
    },
    {
      "id": "weight-management-duration",
      "slug": "weight-management-program-duration",
      "question": "How long should a residential weight-management program be?",
      "short_answer": null,
      "detailed_answer": null,
      "doctor_id": null,
      "read_minutes": null,
      "category": "Doctor Answers",
      "kit_journal": false,
      "locale": "en",
      "source": "gap",
      "status": "draft",
      "featured_image": null,
      "external_references": []
    }
  ],
  "faq": {
    "id": "faq",
    "locale": "en",
    "status": "published",
    "source": "kit",
    "categories": [
      {
        "name": "Booking",
        "faqs": [
          {
            "question": "Is my booking confirmed straight away?",
            "answer": "A stay is confirmed after a preliminary consultation with our doctors. You will be asked to share a health assessment, relevant medical records and your current medication first."
          },
          {
            "question": "How long should I stay?",
            "answer": "Duration depends on the programme and your assessment. Your doctor advises a typical duration after consultation."
          }
        ]
      },
      {
        "name": "Who can stay",
        "faqs": [
          {
            "question": "Who can stay?",
            "answer": "Shantara accepts guests aged 18 to 80 with conditions that can be managed through residential naturopathy. Acute or emergency care is outside what we provide."
          }
        ]
      },
      {
        "name": "During your stay",
        "faqs": [
          {
            "question": "How do meals work?",
            "answer": "Meals are planned as part of your programme, taking into account your doctor's recommendations and dietary requirements."
          },
          {
            "question": "Can I leave the property during my stay?",
            "answer": "Guests usually remain at the retreat during the programme so meals, therapies and reviews can follow the plan. Leaving for a medical emergency is arranged with the team."
          }
        ]
      }
    ]
  },
  "guestStories": [],
  "events": [],
  "testimonials": []
};
